//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.MFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioE", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UsuarioE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasennaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenna {
            get {
                return this.ContrasennaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasennaField, value) != true)) {
                    this.ContrasennaField = value;
                    this.RaisePropertyChanged("Contrasenna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MFService.IMilFraganciasService")]
    public interface IMilFraganciasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/NuevoUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/NuevoUsuarioResponse")]
        int NuevoUsuario(Datos.MFService.UsuarioE usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/NuevoUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/NuevoUsuarioResponse")]
        System.Threading.Tasks.Task<int> NuevoUsuarioAsync(Datos.MFService.UsuarioE usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/EditarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/EditarUsuarioResponse")]
        int EditarUsuario(Datos.MFService.UsuarioE usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/EditarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EditarUsuarioAsync(Datos.MFService.UsuarioE usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/EliminarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/EliminarUsuarioResponse")]
        int EliminarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/EliminarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EliminarUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/BuscarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/BuscarUsuarioResponse")]
        Datos.MFService.UsuarioE BuscarUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/BuscarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<Datos.MFService.UsuarioE> BuscarUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/MostrarUsuarios", ReplyAction="http://tempuri.org/IMilFraganciasService/MostrarUsuariosResponse")]
        Datos.MFService.UsuarioE[] MostrarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/MostrarUsuarios", ReplyAction="http://tempuri.org/IMilFraganciasService/MostrarUsuariosResponse")]
        System.Threading.Tasks.Task<Datos.MFService.UsuarioE[]> MostrarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/AuntentificarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/AuntentificarUsuarioResponse")]
        Datos.MFService.UsuarioE AuntentificarUsuario(Datos.MFService.UsuarioE usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilFraganciasService/AuntentificarUsuario", ReplyAction="http://tempuri.org/IMilFraganciasService/AuntentificarUsuarioResponse")]
        System.Threading.Tasks.Task<Datos.MFService.UsuarioE> AuntentificarUsuarioAsync(Datos.MFService.UsuarioE usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMilFraganciasServiceChannel : Datos.MFService.IMilFraganciasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MilFraganciasServiceClient : System.ServiceModel.ClientBase<Datos.MFService.IMilFraganciasService>, Datos.MFService.IMilFraganciasService {
        
        public MilFraganciasServiceClient() {
        }
        
        public MilFraganciasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MilFraganciasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MilFraganciasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MilFraganciasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NuevoUsuario(Datos.MFService.UsuarioE usuario) {
            return base.Channel.NuevoUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> NuevoUsuarioAsync(Datos.MFService.UsuarioE usuario) {
            return base.Channel.NuevoUsuarioAsync(usuario);
        }
        
        public int EditarUsuario(Datos.MFService.UsuarioE usuario) {
            return base.Channel.EditarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<int> EditarUsuarioAsync(Datos.MFService.UsuarioE usuario) {
            return base.Channel.EditarUsuarioAsync(usuario);
        }
        
        public int EliminarUsuario(int idUsuario) {
            return base.Channel.EliminarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> EliminarUsuarioAsync(int idUsuario) {
            return base.Channel.EliminarUsuarioAsync(idUsuario);
        }
        
        public Datos.MFService.UsuarioE BuscarUsuario(int idUsuario) {
            return base.Channel.BuscarUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Datos.MFService.UsuarioE> BuscarUsuarioAsync(int idUsuario) {
            return base.Channel.BuscarUsuarioAsync(idUsuario);
        }
        
        public Datos.MFService.UsuarioE[] MostrarUsuarios() {
            return base.Channel.MostrarUsuarios();
        }
        
        public System.Threading.Tasks.Task<Datos.MFService.UsuarioE[]> MostrarUsuariosAsync() {
            return base.Channel.MostrarUsuariosAsync();
        }
        
        public Datos.MFService.UsuarioE AuntentificarUsuario(Datos.MFService.UsuarioE usuario) {
            return base.Channel.AuntentificarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<Datos.MFService.UsuarioE> AuntentificarUsuarioAsync(Datos.MFService.UsuarioE usuario) {
            return base.Channel.AuntentificarUsuarioAsync(usuario);
        }
    }
}
